version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment: 
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
    ports:
        - 5432:5432
    volumes:
        - ./volumes/postgres:/var/lib/postgresql/data:delegated